### ISSUE TITLE
Crash when client disconnects before response is sent to it

### ISSUE THREAD

**Issue by terrisgit** [moonthug/hapi-xray#4]
With the hapi-xray plugin enabled, hit a HAPI endpoint that takes a while to respond (e.g., sleep for 10 seconds and return). On the API client side, cancel the request before the response is received. 

The HAPI server process will output the following. Avoid calling getCauseTypeFromHttpStatus if the http status is undefined.

```
(node:33) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'toString' of undefined
    at Object.getCauseTypeFromHttpStatus (/usr/src/app/node_modules/aws-xray-sdk-core/lib/utils.js:22:23)
    at Object.request.server.events.once.req [as listener] (/usr/src/app/node_modules/hapi-xray/lib/xray.js:75:34)
    at module.exports.internals.Podium.internals.Podium.emit (/usr/src/app/node_modules/@hapi/podium/lib/index.js:224:107)
    at Request._finalize (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:447:27)
    at Request._abort (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:423:14)
    at Request._reply (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:377:18)
    at Request._execute (/usr/src/app/node_modules/@hapi/hapi/lib/request.js:216:25)
(node:33) UnhandledPromiseRejectionWarning: Unhandled promise rejection.
```

**Comment by moonthug** [comment]
Resolved in `1.1.1`. The plugin now listens to event from the raw response.
